version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: logitrack-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: logitrackdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - logitrack-net

  app:
    build: ..
    container_name: logitrack-api
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      SPRING_R2DBC_URL: r2dbc:mysql://mysql:3306/logitrackdb?pool=true
      SPRING_R2DBC_USERNAME: root
      SPRING_R2DBC_PASSWORD: root
    ports:
      - "8080:8080"
    networks:
      - logitrack-net

volumes:
  mysql_data:

networks:
  logitrack-net: