version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: logitrack-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: logitrackdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - logitrack-net

  localstack:
    image: !encontrar
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
      - AWS_DEFAULT_REGION=sa-east-1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=9000
      - LAMBDA_EXECUTOR=local
      - START_WEB=1
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=admin
      - EDGE_PORT=4566

  app:
    build: ..
    container_name: logitrack-api
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      SPRING_R2DBC_URL: r2dbc:mysql://mysql:3306/logitrackdb?pool=true
      SPRING_R2DBC_USERNAME: root
      SPRING_R2DBC_PASSWORD: root
    ports:
      - "8080:8080"
    networks:
      - logitrack-net

volumes:
  mysql_data:

networks:
  logitrack-net:
